### ISSUE TITLE
add geographr package 

### ISSUE THREAD

**Issue by HuguesPecout** [rCarto/geomatique_avec_r#1]
R package for mapping UK geographies -> https://github.com/britishredcrosssociety/geographr

A Guide to Working with US Census Data in R -> https://rconsortium.github.io/censusguide/r-packages-all.html

The FedData package  -> https://docs.ropensci.org/FedData/

geoknife package -> http://usgs-r.github.io/geoknife/

Rgeoboundaries -> https://www.geoboundaries.org/

wopr -> https://github.com/wpgp/wopr

elevatr

nasapower

MODIStsp

rdhs

openair

malariaAtlas
--

**Comment by rCarto** [comment]
https://CRAN.R-project.org/package=geodata
https://github.com/rspatial/geodata
geodata: Download Geographic Data
