### ISSUE TITLE
[Ch. 4.3] Digitalisation > Numérisation

### ISSUE THREAD

**Issue by le-jun** [rCarto/geomatique_avec_r#2]
Je suis pas du domaine et peut être que c’est du jargon officiel, mais on parle généralement de numérisation plutôt que de digitalisation qui est un faux-ami.

**Comment by rCarto** [comment]
Bonjour, 
Je pense qu'on est en effet ici dans le vocabulaire spécifique de la carto ou on aurait : 
* Digitalisation d'un fond de carte : numériser des points (lignes et polygones) à partir d'un support visuel, c'est à dire à attribuer à chaque point des coordonnées X et Y dans un système quelconque. (https://georezo.net/wiki/main/dico/digitaliser)
* Numérisation d'une carte : scanner une carte et la géolocaliser (https://www.archimag.com/archives-patrimoine/2020/03/09/methode-ign-numeriser-cartes-anciennes-9-etapes)

**Comment by jdlom** [comment]
Je relance le débat.  
Je pense tout de même que maintenant on devrait parler de _numérisation_ plutôt que digitalisation. La source citée sur georezo date de 2009 et mériterait d'être remise à jour.  Dans les ressources françaises sous qgis (ou arcgis) qu'on trouve en ligne,  on parle à chaque fois de numérisation.

**Comment by rCarto** [comment]
Je pense toujours que le terme *numérisation* est ambigu et concerne le plus souvent le fait de scanner une carte. 
Je sais bien que le terme de *digitalisation*, terme quand même utilisé après 2009, est problématique et que le passage du *digital* au *numérique* en français a été (est) long et douloureux.
Je propose d'utiliser les termes *vectoriser* et *vectorisation* qui me semblent plus spécifiques, plus précis.
